spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/taxi-service-db}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:u}
    password: ${DATABASE_PASSWORD:u}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

server:
  port: ${SERVER_PORT:8080}

sqs:
  enabled: ${SQS_ENABLED:false}
  projections: ${SQS_PROJECTIONS_ENDPOINT:}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.jdbc.datasource.init: ${LOG_LEVEL_SQL:DEBUG}
    org.dga.taxiservice: ${LOG_LEVEL_APP:DEBUG}

